

spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/persondb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
